# Generated by Django 6.0.4 on 2026-05-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Não pago'), ('PAGO', 'Pago')], default='PENDENTE', max_length=10),
        ),
    ]
