# Generated by Django 6.0.4 on 2026-05-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0002_alter_mensalidade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
