# Generated by Django 6.0.4 on 2026-05-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0003_alter_evento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.URLField(blank=True, null=True),
        ),
    ]
