# Generated by Django 6.0.5 on 2026-05-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0004_evento_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
    ]
