# Generated by Django 6.0.5 on 2026-05-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0005_evento_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='corda',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='graduacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
