# Generated by Django 6.0.5 on 2026-06-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0006_aluno_corda_aluno_graduacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
